services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=press
      - MYSQL_DATABASE=RETROGAME
      - MYSQL_USER=Rinesa
      - MYSQL_PASSWORD=nesa
    ports:
      - 56780:3306
volumes:
  db_data:<